import type { VectorDefinition } from './types';

export const VECTOR_DEFINITIONS: VectorDefinition[] = [
  // Technical
  {
    id: 'technical',
    category: 'technical',
    name: 'technical',
    label: 'Indicadores Técnicos',
    description: 'RSI, MACD, Bollinger Bands, EMA, ADX, ATR - Análisis técnico completo basado en indicadores clásicos',
    icon: 'TrendingUp',
    color: '#10b981',
    defaultEnabled: true,
    defaultWeight: 1.0,
  },
  {
    id: 'pattern',
    category: 'pattern',
    name: 'pattern',
    label: 'Patrones de Vela',
    description: 'Doji, Hammer, Engulfing, Morning/Evening Star, Pin Bar - Detección de patrones de velas japonesas',
    icon: 'CandlestickChart',
    color: '#f59e0b',
    defaultEnabled: true,
    defaultWeight: 1.2,
  },
  {
    id: 'volume',
    category: 'volume',
    name: 'volume',
    label: 'Análisis de Volumen',
    description: 'Volume Profile, OBV, Acumulación/Distribución - Análisis del flujo de dinero institucional',
    icon: 'BarChart3',
    color: '#6366f1',
    defaultEnabled: true,
    defaultWeight: 1.1,
  },
  {
    id: 'news',
    category: 'news',
    name: 'news',
    label: 'Análisis de Noticias',
    description: 'IA analiza noticias financieras, earnings, eventos corporativos y evalúa impacto en el precio',
    icon: 'Newspaper',
    color: '#ef4444',
    defaultEnabled: true,
    defaultWeight: 1.3,
  },
  {
    id: 'sentiment',
    category: 'sentiment',
    name: 'sentiment',
    label: 'Sentimiento de Mercado',
    description: 'Fear & Greed Index, sentimiento social (Twitter/X, Reddit), flujo de opciones put/call',
    icon: 'Brain',
    color: '#8b5cf6',
    defaultEnabled: true,
    defaultWeight: 0.8,
  },
  {
    id: 'macro',
    category: 'macro',
    name: 'macro',
    label: 'Análisis Macroeconómico',
    description: 'Decisiones de la Fed, calendario económico, tasas de interés, datos de inflación y empleo',
    icon: 'Building2',
    color: '#06b6d4',
    defaultEnabled: true,
    defaultWeight: 0.7,
  },
  {
    id: 'orderflow',
    category: 'orderflow' as const,
    name: 'orderflow',
    label: 'Order Flow (Próximamente)',
    description: 'Análisis del flujo de órdenes, libro de órdenes y microestructura del mercado — aún no implementado',
    icon: 'BarChart3',
    color: '#f97316',
    defaultEnabled: false, // Off by default — not yet implemented
    defaultWeight: 1.1,
    isSimulated: true, // Flag: this vector is not yet implemented
  },
];
